name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build-push-images:
    name: Build and push appointment-sample-ui
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v2
        with:
          push: true
          target: release
          build-args: |
            REACT_APP_AUTH0_DOMAIN=${{ secrets.REACT_APP_AUTH0_DOMAIN }}
            REACT_APP_AUTH0_CLIENT_ID=${{ secrets.REACT_APP_AUTH0_CLIENT_ID }}
            REACT_APP_AUTH0_AUDIENCE=${{ secrets.REACT_APP_AUTH0_AUDIENCE }}
            REACT_APP_AUTH0_NAMESPACE=${{ secrets.REACT_APP_AUTH0_NAMESPACE }}
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/appointment-sample-ui:latest
